### ISSUE TITLE
What should be listed in `setup.py`'s `install_requires`?

### ISSUE THREAD

**Issue by dominiquesydow** [volkamerlab/klifs_utils#2]
#### My previous understanding of `setup.py`'s `install_requires`

When using `pip install`, `pip` will look up the `setup.py` file in `klifs_utils`. In this `setup.py` file I list all package requirements. 

So: I thought I am supposed to add all packages there that I am using in `klifs_utils`. Now I think I am misunderstanding why we list packages there in the first place :)

#### The source of my confusion

I added `rdkit` to `klifs_utils`'s `setup.py` file.

Before (`pip install -e klifs_utils` is successfull):
```
install_requires=['pandas', 'bravado', 'biopandas']
```
Now (`pip install -e klifs_utils` fails):
```
install_requires=['pandas', 'bravado', 'biopandas', 'rdkit']
```
I understand (I think) that it was not a clever idea to add `rdkit` here since it does not offer a `pip` installation (it uses `conda`).

Here the full error message:

```bash
$ pip install git+https://github.com/volkamerlab/klifs_utils.git@lib-skeleton
Collecting git+https://github.com/volkamerlab/klifs_utils.git@lib-skeleton
  Cloning https://github.com/volkamerlab/klifs_utils.git (to revision lib-skeleton) to /tmp/pip-req-build-u8i12sro
  Running command git clone -q https://github.com/volkamerlab/klifs_utils.git /tmp/pip-req-build-u8i12sro
  Running command git checkout -b lib-skeleton --track origin/lib-skeleton
  Switched to a new branch 'lib-skeleton'
  Branch 'lib-skeleton' set up to track remote branch 'lib-skeleton' from 'origin'.
Requirement already satisfied: pandas in ./anaconda3/lib/python3.6/site-packages (from klifs-utils==0+untagged.38.g7dc2105) (0.23.0)
Collecting bravado
  Using cached bravado-10.5.0-py2.py3-none-any.whl (36 kB)
Collecting biopandas
  Using cached biopandas-0.2.5-py2.py3-none-any.whl (263 kB)
ERROR: Could not find a version that satisfies the requirement rdkit (from klifs-utils==0+untagged.38.g7dc2105) (from versions: none)
ERROR: No matching distribution found for rdkit (from klifs-utils==0+untagged.38.g7dc2105)
```

#### My question

Why do we list packages in the `setup.py`?
1. We cannot list all dependencies for the library if e.g. a package cannot be installed via `pip`.
2. Apparently the `setup.py` file in combo with `pip` will not install packages for us, since we need to install these packages manually anyways (in our case using `conda-env`). So what is `install_requires` for?

**Comment by dominiquesydow** [comment]
This is a note to myself to do more reading about what `pip` is doing:

I have multiple branches in my `git` folder. The `setup.py` files differ in these branches (e.g. `master` has no information about `install_required`). 

Even though, `pip install` seems to run the `setup.py` from the `lib-skeleton` branch. 

How can `pip` deal with multiple `setup.py` files? 
I assume it is not choosing `lib-skeleton`'s `setup.py` file over `master`'s - why should it?

**Comment by jaimergp** [comment]
Outside data science, `conda` is not really popular and everything happens through `PyPI` and `pip`. `install_requires` is the `pip`-way to specify dependencies. But of course, these dependencies must be available on https://pypi.org/, a repository that has nothing to do with `conda`. Conda can use `pypi` though, thanks to the `- pip:` entry in environment files.

So: conda knows about pip, but not the other way around.

Why do we use both? Well, historic reasons... when we build a conda recipe, we do install our own package with `pip`, BUT we specify an additional flag to ignore `setup_requires`:

```
pip install <package> --no-deps
```

If you want, you can ignore `install_requires` for now and focus on the conda env file.

When you specify a git address (or a ZIP file in an online resource, which is usually faster), it defaults to `master`, so I don't know how it might be getting `lib-skeleton`. Are you sure?
